language: python
python: 3.6
install:
- pip install -r requirements.txt
script:
- python setup.py test
- python setup.py sdist bdist_wheel
env:
  global:
  - secure: aQeivcjtHIgQ7zPWq6b/pgPcXGaWD2Ds/Ve1At4mFgATG8q0a/rUe3TPS9obKPYTu2IyF/Vk6k31kspNux9/ZGWjwXmdJ7aDCz6SG5VR1qDiZmXfF9cSyJ0LfV8ifcu9q+tdNPwvTVvb8YE1Tc74lzQENalz1DTQHTHHna/e1GSVMsxo83DYuEtryIVrvmwKpGeolaMAgccFyD5nyVylxtcBtC5joutG6pZZnDBUE7OGrfIR1GIw8OFQCjhxq/jcEJwKJzxmDY6D3auBbq470t5WTwvbL9Knn4waYnQl9cyVaoG/JdBk4UNt92weSZLTSzbFnFGNBtvTZ2n+0hy7wX2M/ekXtLBje2NPKm6THCKJqv75CzDjUavasF2nttUrZRsogRlXWiyna9Va9g0Kruv9sAvawzVzEXYd03Vo17BVI9X2qjUEv1bNVvVGcHfFyHuIpuIw+zX6eCQHPtbpTGumy6FiE8HCX2SV0m2F4/uoFEQAGk+bO86c4PRN1WJ8fcxxPMA6LcAwFJQRZ3aKhsitwbkB8G1ADx+PQ3A3grSdMUXaLi9Cmy4LEr33l3cIGpocZsfef4JEGh83zoGBN+7MYvFbaiUSl0Eb6LBAXCO+f9lP762D2MkL+2T4obtJHIEEMCpjEb5ajHxwTocs2vdnHx4SuAmHf0I/vymcVXE=
  - secure: fdfpHIwrWE2qHxnuuxonRiVRNAcw964mVRv3CF0fsKJqQN5XZ4zKu4g94zlSWLtSicKOqYbxIdbM2r1Qg9wdfqwT06GNPxZnIx0825h42Jqq0SOtaUoT8WxLD+wo8XtWKutyjhqlifAb5avFFYXlvp1+N8ty0ZcWRcqLqE6AnMITRwF5tzX26V7XkZJGW6g1/SPMlg+0tWQL6UVgJPrtzUt7acoYAYyYsJGHOlUkUVKdypgE9fRn4evG2R7xizbw4Xt6QzCFf7++7uTlC0PZliS+piPYSmiaVleGOM59G0Xg7U4YH6N3X8E7DyegwxE4ZzGhNHZ8ngWOb5gMWVWmjxbjd39QQai+XzJYGuSYdkJoeAlAvDeaOwRl4uXdB8cNtr4CRT2AcU/q6YrK8wGNP2J2ms/m4RhnYB82/C+0JxAE4V67VeIpKY7iA+g1sFQxb5xIWevW13pr4Aoz/0SnKbVVdfHpatxeYbdvQw8+2rsAG3day34ITcITekBt0VmqKy7K2jrwhKGyWP2H1GG8EQ94+VhyqRaAO5lYnJu9C7YxX3BOTkIIrFgJ8baJOwku9D/nWOOuKyHRrAX/iooX9GqNOh4fBydfbBhtehbmJaLpTVL7Vd6mVMdnz/pROuDbCYQPkPv/R54bjBx9vwiRwRyyEuVfZK/J+3IPZyDDD1A=
deploy:
  provider: pypi
  user: $PYPI_USER
  password: $PYPI_PASS
  on:
    tags: true
  distributions: sdist bdist_wheel
  skip_existing: true
