language: python
python: 3.6
install:
- pip install -r requirements.txt
script:
- python setup.py test
- python setup.py sdist bdist_wheel
deploy:
  provider: pypi
  user:
    secure: JFl3rDv/VDP6kx0s7dR/wlXcwR3ULK7PjUE/ppDxFn9TImmlCwAdfvaykLTru7DHj+s4qCCSqKAIfFtnP7Nz47pvUuolxxQXc6jtcMmjGIt5gR9txZvoR2fVYMJkdu28pJ4gdM/efdY2V7HrTvRbJYEDKnE2xPKyMaa68P8wOaRrZzkUyoe0GQrlosyMBoMXds1g9maVed7KdetNR0rx6OQvh2F6/4JTo5pmWo2uYtG1lLt6quzAUhENdnIZT1yjmEPOlwllXbEH+dD2WYY05gBKtj/3WKRtoKJNvD0byJCCXIMp9Z4LrOZMYMIyVpgLiRRHBFt5Rc7OcS/LrDsIjaWK37Rl2KhhggfXtymkp1B/j/Zepal0WbL/H+RnbXp/jSVYto+pgECqlluCYgOEnQraIGqYoDWMu2ORMXfmbVw8LQe7RwZok9tDNY0JQ8c7kqrGO14bBROBKOHCNHAf70Ar5zUXffUCPpkFtp4s03r4v8F+IBoMObg2sCocj1Vs94dyI8XJWHc7asNW9xfUQm9fDmZbdpAUGkAepzIvoLj/zi78zPqjsip0cOFLnD3Rlhq/9OHRTTv/Y1aM+IfVX4B06PwYempRGgqaPrnE7+Io05XH0Izy9qWIKeMu2L4YzGV74LjI6w96KI+Tsut9He1SC5d4NThFxA4LIXWLJIU=
  password:
    secure: esBwb+PJfu7SRpgPcKaFnsS7bwZ8CDK57zo7P4tLSFE90dkD+BxAm+iQOkjfk72cbScXIBWGzMl2n4RIlBV8828FpZNnuJA8SzcNbnV9vCC5PtiwvOoRBZiSxV6Bank1bVG9gG1zQMXCfEuB55W6pBl7lOcRHF4qPGitwEKnnvG/rsxrWxUUlDYgf68WuIp91dmJWHDozJou4M/2ZYm1+OQ1E+A4RLgmXvHmrn9Z+H8wP/bqhMxPzbpMQjkgPc0X6YPTzdAs/yP4HvAbNCv3RUPC4sbmlRHvBLlzbyvqjp2P4/OQj2B+s5L+2b+uMJp4kkyEj0iZeLSqfLmT94xM8nQ4xOFmDMqvMQOrXvuvVjx3C+6TYwbVR535TqJCB5RUszGUojqVCjy5JXa84Y4aof2Vo+/X3EFNl6eJZtn+pyzl68taS0XLm05kjafS/AnIVD5IcJB8v+9uF/m78Oeas3kHm0xT5sHSo7j7WaBSXDsdLezgNtW4T7t79Ke05QblZxpa/ZEA/dPgU61Nyr+bvlZfswV5ggOUkD63OuyZpIKApMdiGytr96Bwd6SnkRpRjxYsOyaQ215Dy2h04Bcum6/u0GkyTEa0rR0rnsUtZ7B7MIpuAayaenLBDhg3h7FcJ+rAILCQQsvGIPuaIq28moSP2YEJCmDWldPiHwhsbr4=
  on:
    tags: true
  distributions: "sdist bdist_wheel"
  skip_existing: true